spring:
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 9091
myjwttoken:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: ${JWT_SECRET_KEY}