spring:
  liquibase:
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    rememberMe:
      key: ${REMEMBER_ME_KEY}
server:
  port: ${SERVER_PORT:9091}
myjwttoken:
  app:
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
    jwtSecret: ${JWT_SECRET_KEY}